### PR TITLE
Add support for shared workers

### PR DESCRIPTION
**Pull request by stutrek**
Title sums it up. This adds support for SharedWorker. The API is the same. Tests were added too.

### CODE REVIEW

**Comment by stutrek** [comment]
@googlebot I signed it!

**Comment by stutrek** [comment]
@developit any chance you could take a look? Thanks.

**Comment by lasseborly** [comment]
This would be great to have merged @developit :+1:

**Comment by skmvasu** [comment]
Any plans to merge this? @developit  Happy to help incase there is an issue and needs to be fixed. This will help us out in a few projects

**Pull request merged**
